### ISSUE TITLE
데스크톱 화면 뷰 구성 및 스타일 수정

### ISSUE THREAD

**Issue by saseungg** [saseungg/joonggo-moa#2]
## ☑️ 진행할 작업
기존 레이아웃을 모바일 화면에 맞춘 레이아웃 사이즈로 고정시키고 데스크톱 화면일 경우 다른 상호작용을 할 수 있도록 화면 구성

## 📝TODO
- [x] 레이아웃 컴포넌트 구현
- [x] 페이지별 레이아웃 적용
- [x] 미디어 쿼리를 이용해서 뷰포트 사이즈가 커졌을 시 레이아웃 처리
- [x] 스크롤, top button 스타일 수정
- [x] Product item 좋아요, 채팅 스타일 수정
- [x] 아이콘 사이즈 props 설정
- [x] 레이아웃 적용으로 인해 깨지는 스타일 수정
- [x] 모달 루트 위치 수정
- [x] 드롭다운, 팝업 스타일 수정

## ⚙️기타
고민 거리 : 데스크톱 화면일 시 어떤 기능을 처리할지 고민해보기
